---
title: "backtest-summary"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(googlesheets4)
library(tidyverse)
library(data.table)
library(magrittr)
library(quantmod)
library(TTR)
library(plotly)
library(igraph)
library(visNetwork)
```

## R Markdown

```{r}
data_path <- "~/Documents/projects/StockScreeningStrategies/data/"

backtest <- read_csv(paste0(data_path, "backtest-screen-pattern-match.csv")) %>%
  filter(monday_open > 0) %>%
  mutate(percent_change = friday_close / monday_open)
```


```{r data_sum}

topn <- backtest %>% 
  filter(friday_close>0,
         screen_type == "percent", 
         screen_avg_change > 1.1, 
         screen_prop_up==1) %>%
  group_by(buy_date) %>% 
  arrange(-screen_avg_change) %>% 
  top_n(n = 1)



dat <- topn %>% 
  group_by(buy_date) %>% 
  summarise(gross = sum(percent_change), total = n(), return = gross/total) %>% 
  filter(return > 0) %>% 
  ungroup %>%
  mutate(cumprod = round(cumprod(return), 3))

```

## Including Plots

```{r}

topn %>% ungroup %>% ggplot(., aes(x = screen_avg_change, y = percent_change)) + geom_point()

```


```{r pressure, echo=FALSE}
by_type <- ggplot(backtest, aes(x = buy_date, y = percent_change, color = screen_type)) + geom_point()
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
